server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://daily-pay.cgkscirb0xic.ap-northeast-2.rds.amazonaws.com:3306/prod?serverTimezone=UTC
    password: ss49594959
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

logging:
  level:
    com.hyerijang.dailypay: info