name: CI/CD using github actions & docker

# event trigger
# 새로운 Release tag 생성 시 수행 (github Release Tag)
on:
  push:
    tags:
      - 1.**

permissions:
  contents: read

# 실제 실행될 내용들을 정의합니다.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Open jdk 17 버전 환경을 세팅
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Gradle caching - 빌드 시간 향상
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      #Set up Gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Github Submodule에서 환경변수 가져옴
        uses: actions/checkout@v4
        with:
          token: ${{secrets.CONFIG_TOKEN}}
          submodules: true

      - name: Docker를 위해 프로젝트 메타정보 추출
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/daily-pay
          # 가장 최신 image 에 latest tag 달기
          flavor: |
            latest=true
          # Git short commit, use git version tag
          tags: |
            type=semver,pattern={{version}}

      - name: Gradle 빌드 수행
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Docker 이미지 Build 및 push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: EC2 서버에 배포
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.SSH_KNOWN_HOSTS }} # EC2 퍼블릭 IPv4 DNS
          username: ${{secrets.SSH_USER}}
          key: ${{ secrets.SSH_PEM_KEY }}
          envs: GITHUB_SHA
          # 주의 : 실행중인 컨테이너 전부 종료
          script: |
            sudo docker stop $(sudo docker ps -a -q)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/daily-pay
            sudo docker run -d -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/daily-pay
            sudo docker image prune -f